version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend
  backend:
    image: nestjs-app
    ports:
      - "3000:3000"
